### ISSUE TITLE
On the "Filter changesets" screen there's no way to filter text from the middle column

### ISSUE THREAD

**Issue by SomeoneElseOSM** [Zaczero/Thanos#6]
For example, displayed is "#123456789 by user_12345678" (and various colourful things of unclear meaning).

I'm like to be able to copy and paste "user_12345678" somewhere else, but there seems to be no way to do it.

**Comment by Zaczero** [comment]
I believe you should watch the video tutorial for Thanos that I sent to (Fizzie/DWG). It covers all the fundamental aspects. Essentially, the buttons on the right correspond to "u" for user and "c" for comment. The color of the button, whether green, white, or red, indicates which section the group should be moved to: Green for Legitimate, White for Uncategorized, and Red for Malicious. If you wish to automatically revert everything associated with "user_12345678," simply click the red dot button next to the "u" (user). :slightly_smiling_face: 

![image](https://github.com/Zaczero/Thanos/assets/10835147/9c17c008-d266-41b2-908b-4871033fce3f)

**Comment by Zaczero** [comment]
If you happen to forget, there's a tooltip that appears when you hover over it for a while:

![image](https://github.com/Zaczero/Thanos/assets/10835147/edfe8844-c96b-4a6a-a797-1e1b1fd4f28c)

**Comment by SomeoneElseOSM** [comment]
>  video tutorial 

I'm not really a "watching a video" sort of person :)

**Comment by Zaczero** [comment]
*Transcribed + formatted*

### Introduction
This is a brief tutorial on using Thanos, an application designed to revert mass vandalism and potentially for further automation tasks in the future.

### Initial Setup
After logging in, the first step is to query for the chain sets. You should provide a time range and, optionally but recommended, include tags to speed up the operation. In this example, we'll focus on vandalism that occurred on the 26th, starting at 12:00 PM UTC and ending at 4:00 AM on the 27th.

### Chain Set Tags
Next, provide the chain set tags. In our example, the vandalism was localized in the UK, so use `local=UK` (case-sensitive). You can also optimize the query by checking for the host, a method I usually use to revert changes.

### Submitting Query
Once the query details are confirmed, submit the query. The first query might take a bit longer due to stale cache and downloading user data. After that, you'll see the uncategorized chain sets, some of which might be deleted or blocked accounts. 

### Sorting Accounts
Move deleted and blocked accounts to the "Malicious" category. You can also move accounts to the "Legitimate" category if they weren't involved in the vandalism.

### Revert Process
Now you'll see a screen similar to the regular revert website. You can optionally add Overpass QL filters, comments, and automatic discussions. A new feature called "Revert to Date" is available to improve efficiency. This feature works best in "Tags Only" mode.

### Final Steps
Before starting the revert process, acknowledge that the vandalism has stopped to avoid suboptimal results. Then start the revert. You will see the progress, but it doesn't update in real-time; you'll have to refresh the page manually.

### Monitoring and Aborting
During the revert process, you can monitor its progress. If you need to abort, there's an option for that. Once the task is complete, you'll see a green checkmark indicating its completion status.

### Tips and Additional Info
- Only moderators, administrators on OpenStreetMap, and whitelisted users can log into this instance.
- You can see who started a revert task in the logs.
- If you have feature requests or need further clarification, you can contact me through my OpenStreetMap account.

---
Thank you for using Thanos. Feel free to reach out if you have any questions or feature requests.

**Comment by Zaczero** [comment]
I'll close down the issue as I am going to assume it's been resolved.
